version: '3'

services:
  postgres:
    container_name: database-rnf
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  backend:
   container_name: backend     
   build: .       
   restart: always     
   ports: 
     - "3001:3001"  # Porta em que o backend vai escutar     
   depends_on: 
     - postgres  # Dependência do serviço do banco de dados